## Secrets ##

secrets:
  mysql_password:
    file: $DOCKERDIR/secrets/mysql_password
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  tunnel_token:
    file: $DOCKERDIR/secrets/token.json
  discord_webhook:
    file: $DOCKERDIR/secrets/discord_webhook


## Networks ##
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  #t2_proxy:
    #name: t2_proxy
    #driver: bridge
    #ipam:
      #config:
        #- subnet: 192.168.90.0/24

include:
  ## Services ##
  # Prefix htpc
  # HOSTNAME = htpc - defined in .env

  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dozzle.yml

  # Homepages
  #- compose/$HOSTNAME/homepage.yml

  # Media
  - compose/$HOSTNAME/plex.yml
  - compose/$HOSTNAME/nzbget.yml
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/overseerr.yml
  - compose/$HOSTNAME/tautulli.yml

  # Utilities
  - compose/$HOSTNAME/docker-gc.yml
  - compose/$HOSTNAME/mariadb.yml
  - compose/$HOSTNAME/watchtower.yml

  # Project Management
  - compose/$HOSTNAME/plane.yml

  # Tunnel
  - compose/$HOSTNAME/tailscale.yml
  - compose/$HOSTNAME/cloudflared.yml
