services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NZBGET_USER=/run/secrets/nzbget_username
      - NZBGET_PASS=/run/secrets/nzbget_password
    volumes:
      - $DOCKERDIR/appdata/nzbget/config:/config
      - $DATADIR/data/usenet:/data/usenet #optional
    ports:
      - 6789:6789
    restart: unless-stopped
    secrets:
      - nzbget_username
      - nzbget_password
