services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/nzbget/config:/config
      - $DATADIR/data/usenet:/data/usenet #optional
    ports:
      - 6789:6789
    restart: unless-stopped
