services:
    tailscale:
      container_name: tailscale
      hostname: tailscale
      image: tailscale/tailscale:latest
      network_mode: 'host'
      volumes:
        - $DOCKERDIR/appdata/:/var/lib # State data will be stored in this directory 
        - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
      cap_add:
        - net_admin
        - sys_module
      environment:
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_USERSPACE=false
        - TS_DEBUG_FIREWALL_MODE=auto
      command: tailscaled
      privileged: true
      restart: unless-stopped
